DECLARE
  VID      NUMBER(5);
  VIDA     NUMBER(5) := 0;
  VTN      VARCHAR2(50) := 201701101017491;
  VCREATE_TIME DATE;
  VDATAFIM DATE;
  VTEMPO   INTERVAL DAY(9) TO SECOND;
  I NUMBER := 1;
  CURSOR C_ID
  IS
    SELECT TH.STATE_ID, TH.CREATE_TIME
    FROM TICKET_HISTORY TH
    JOIN TICKET T ON T.ID = TH.TICKET_ID
    WHERE T.TN = VTN ORDER BY TH.CREATE_TIME ASC, TH.STATE_ID;
BEGIN
  FOR R_ID IN C_ID
  LOOP
  
    IF R_ID.STATE_ID = VIDA OR VIDA = 0 THEN
      VCREATE_TIME := R_ID.CREATE_TIME;
      VIDA := R_ID.STATE_ID;
      DBMS_OUTPUT.PUT_LINE('FALSO: ' || I);
      
    ELSIF R_ID.STATE_ID != VIDA AND R_ID.STATE_ID = 41 THEN
      VTEMPO := (R_ID.CREATE_TIME - VCREATE_TIME) DAY(9) TO SECOND;
      DBMS_OUTPUT.PUT_LINE('EXECUTOU: ' || I);
      I := I + 1;
    END IF;
    VID := R_ID.STATE_ID;
    DBMS_OUTPUT.PUT_LINE(VID || ' ' || VTEMPO);
    --SELECT
  END LOOP;
END;
/


SELECT T.TN, A.ID, TRUNC(A.CREATE_TIME,'MI') CREATE_TIME FROM TICKET T
JOIN ARTICLE A ON T.ID = A.TICKET_ID
JOIN TICKET_HISTORY TH ON T.ID = TH.TICKET_ID
WHERE T.TN = 201701101017491 GROUP BY T.TN, A.ID, TRUNC(A.CREATE_TIME,'MI')
ORDER BY A.ID ASC;

SELECT A.* FROM ARTICLE A JOIN TICKET T ON T.ID = A.TICKET_ID WHERE T.TN = 201701101017491 ORDER BY A.ID;

SELECT * FROM CSSJ_CHAMADOS_OTRS WHERE DT_FECHAMENTO IS NULL;
